// apps/cf-ai-demo/src/App.tsx
import './styles/styles.css';

import { UIRouter } from '@airlib/react';
import { hydrateRoot } from 'react-dom/client';
import { router } from './lib/router.js';
import { RootLayout } from './pages/layout.js';

// Ensure route & IRPC constructors are bundled in the browser client
import './pages/constructor.js';
import './pages/page.js';

router.activate(window.location.href).then(() => {
  hydrateRoot(
    document.getElementById('root')!,
    <UIRouter router={router} root={RootLayout} headless={true} resetScroll />
  );
});

// demos/solid-demos/src/App.tsx
import './styles/styles.css';

import { UIRouter } from '@airlib/solid';
import { render } from 'solid-js/web';
import { router } from './lib/router.js';
import { RootLayout } from './pages/layout.js';

router.activate(window.location.href).then(() => {
  const root = document.getElementById('root')!;
  root.innerHTML = '';
  render(() => <UIRouter router={router} root={RootLayout} headless={true} resetScroll />, root);
});
