// ui/react-form/src/inputs/NumberInput.tsx
import type { Bindable } from '@anchorlib/react';
import type { InputHTMLAttributes } from 'react';
import { createInput } from './createInput.js';

export interface NumberInputProps extends Omit<InputHTMLAttributes<HTMLInputElement>, 'value'> {
  errorClass?: string;
  value?: Bindable<number>;
}
export const NumberInput = createInput<NumberInputProps>('number');

// ui/solid-form/src/inputs/NumberInput.tsx
import type { Bindable } from '@anchorlib/solid';
import type { JSX } from 'solid-js';
import { createInput } from './createInput.js';

export interface NumberInputProps extends Omit<JSX.InputHTMLAttributes<HTMLInputElement>, 'value'> {
  errorClass?: string;
  value?: Bindable<number>;
}
export const NumberInput = createInput<NumberInputProps>('number');
