// ui/react-form/src/inputs/PasswordInput.tsx
import type { Bindable } from '@anchorlib/react';
import type { InputHTMLAttributes } from 'react';
import { createInput } from './createInput.js';

export interface PasswordInputProps extends Omit<InputHTMLAttributes<HTMLInputElement>, 'value'> {
  errorClass?: string;
  value?: Bindable<string>;
}
export const PasswordInput = createInput<PasswordInputProps>('password');

// ui/solid-form/src/inputs/PasswordInput.tsx
import type { Bindable } from '@anchorlib/solid';
import type { JSX } from 'solid-js';
import { createInput } from './createInput.js';

export interface PasswordInputProps extends Omit<JSX.InputHTMLAttributes<HTMLInputElement>, 'value'> {
  errorClass?: string;
  value?: Bindable<string>;
}
export const PasswordInput = createInput<PasswordInputProps>('password');
