// demos/react-demos/src/pages/auth/signin/page.tsx
import { createForm, TextInput, PasswordInput, Checkbox, FormSubmit } from '@airlib/react-form';
import { Meta, page, Title, mutable } from '@anchorlib/react';
import { z } from 'zod';
import { signIn } from './function.js';
import { signInRoute } from './route.js';

const schema = z.object({
  email: z.string().email('Invalid email address'),
  password: z.string().min(8, 'Password must be at least 8 characters'),
  remember: z.boolean().optional().default(false),
});

const SignInForm = createForm(schema);

export const SignInPage = page(signInRoute).render(() => {
  const auth = mutable({ submitted: false, error: '' });

  return (
    <>
      <Title>Sign In — AIR Stack</Title>
      <Meta name="description" content="Sign in to your account." />

      <SignInForm
        className="air-card-group w-md gap-2"
        onSubmit={async (data) => {
          auth.error = '';
          try {
            await signIn({ email: data.email, password: data.password });
            auth.submitted = true;
          } catch (err: any) {
            auth.error = err.message || 'An error occurred';
          }
        }}
      >
        <div className="air-card air-card-body p-10 gap-3">
          {auth.error ? <p className="air-body-sm text-error text-center">{auth.error}</p> : null}

          <SignInForm.Field name="email" label="Email">
            <TextInput placeholder="jane@example.com" />
          </SignInForm.Field>

          <SignInForm.Field name="password" label="Password">
            <PasswordInput placeholder="••••••••" />
          </SignInForm.Field>

          <div className="flex flex-col gap-2 mt-3">
            <SignInForm.Field name="remember">
              <label className="flex items-center gap-3 cursor-pointer">
                <div className="flex h-5 items-center">
                  <Checkbox />
                </div>
                <span className="air-body-md text-on-surface">Remember me</span>
              </label>
            </SignInForm.Field>
          </div>
        </div>

        <div className="air-card-filled air-card-body p-10">
          <FormSubmit className="air-button w-full">{(form) => (form?.pending ? 'Signing In...' : 'Sign In')}</FormSubmit>

          {auth.submitted ? <p className="air-body-sm text-primary text-center mt-2">Welcome back!</p> : null}
        </div>
      </SignInForm>
    </>
  );
});

export default SignInPage;

// demos/solid-demos/src/pages/auth/signin/page.tsx
import { $bind, derived, form, Meta, mutable, page, Title } from '@airlib/solid';
import type { JSX } from 'solid-js';
import { z } from 'zod';
import { CheckboxField } from '../../../components/CheckboxField.js';
import { InputField } from '../../../components/InputField.js';
import { signIn } from './function.js';
import { signInRoute } from './route.js';

const schema = z.object({
  email: z.string().email(),
  password: z.string().min(8),
});

function SignInForm() {
  const [credentials, errors] = form(schema, { email: '', password: '' });
  const auth = mutable({ submitted: false, remember: false, error: undefined });

  const handleSubmit: JSX.EventHandlerUnion<HTMLFormElement, SubmitEvent> = async (e) => {
    e.preventDefault();
    if (errors.email || errors.password) return;

    try {
      await signIn({ email: credentials.email, password: credentials.password });
      auth.submitted = true;
    } catch (err) {
      auth.error = err;
      console.error(err);
    }
  };

  const isDisabled = derived(() => !!(errors.email || errors.password));
  const submitMessage = derived(() => (auth.submitted ? `Welcome back, ${credentials.email}!` : ''));
  const errorMessage = derived(() => auth.error?.message);

  return (
    <form class="auth-form" onSubmit={handleSubmit}>
      <InputField
        id="signin-email"
        type="email"
        label="Email"
        value={$bind(credentials, 'email')}
        error={errors.email}
      />
      <InputField
        id="signin-password"
        type="password"
        label="Password"
        value={$bind(credentials, 'password')}
        error={errors.password}
      />
      <CheckboxField id="signin-remember" label="Remember me" checked={$bind(auth, 'remember')} />
      <button type="submit" class="btn-counter" disabled={isDisabled.value}>
        Sign In
      </button>
      {submitMessage.value ? <p class="submit-message">{submitMessage.value}</p> : null}
      {errorMessage.value ? <p class="error-message">{errorMessage.value}</p> : null}
    </form>
  );
}

export const SignInPage = page(signInRoute).render(() => (
  <>
    <Title>Sign In — AIR Stack</Title>
    <Meta name="description" content="Sign in to your account." />
    <SignInForm />
  </>
));
export default SignInPage;
