// ui/solid-form/src/inputs/Textarea.tsx
import { type AnyType, formInput } from '@airlib/form';
import { type Bindable, derived, setup } from '@anchorlib/solid';
import type { JSX as Jsx } from 'solid-js';
import { getInputClasses, INPUT_OPTIONS_KEYS, TEXTAREA_OPTIONS, TEXTAREA_OPTIONS_KEYS } from '../config.js';

export interface TextareaProps extends Omit<Jsx.TextareaHTMLAttributes<HTMLTextAreaElement>, 'value'> {
  errorClass?: string;
  value?: Bindable<string>;
}

export const Textarea = setup<TextareaProps>((props) => {
  const restProps = props.$omit([
    'value',
    'name',
    'disabled',
    'class',
    'onInput',
    'onBlur',
    ...(TEXTAREA_OPTIONS_KEYS as never[]),
    ...(INPUT_OPTIONS_KEYS as never[]),
  ]);
  const input = formInput(props as AnyType);
  const { baseClass, errorClass } = getInputClasses(TEXTAREA_OPTIONS);

  const handleInput = (e: Event) => {
    input.value = (e.currentTarget as HTMLTextAreaElement).value;
    if (typeof props.onInput === 'function') {
      props.onInput(e as AnyType);
    }
  };

  const handleBlur = (e: Event) => {
    input.settled();
    if (typeof props.onBlur === 'function') {
      props.onBlur(e as AnyType);
    }
  };

  const className = derived(() => {
    if (input.touched && (input.error || !input.matched)) {
      return [props.class ?? baseClass, props.errorClass ?? errorClass].filter(Boolean).join(' ');
    }
    return props.class ?? baseClass;
  });

  return (
    <textarea
      {...restProps}
      name={input.name}
      value={input.value}
      disabled={input.disabled}
      class={className.value}
      onInput={handleInput}
      onBlur={handleBlur}
    />
  );
});

// ui/react-ui/src/form/textarea/Textarea.tsx
import { formInput } from '@airlib/form';
import { classx } from '@airlib/headless/utils';
import { derived } from '@anchorlib/core';
import { type Bindable, render, setup } from '@anchorlib/react';
import type { ComponentProps, InputEventHandler } from 'react';
import { TEXTAREA_CONFIGS } from './config.js';

export interface TextareaProps extends Omit<ComponentProps<'textarea'>, 'value' | 'size' | 'children'> {
  size?: 'sm' | 'md' | 'lg';
  variant?: 'outlined' | 'filled';
  value?: Bindable<string>;
}

export const Textarea = setup<TextareaProps>((props) => {
  const input = formInput<string>(props);
  const restProps = props.$omit(['variant', 'className', 'value', 'onInput', 'placeholder', 'size']);
  const fieldId = props.id || input.name.replace(/\./g, '-');
  const errorId = `${fieldId}-error`;

  const handleInput: InputEventHandler<HTMLTextAreaElement> = (e) => {
    input.value = e.currentTarget.value;
    props.onInput?.(e);
  };

  const hasError = derived(() => input.touched && (input.error || !input.matched));

  return render(
    () => (
      <textarea
        {...restProps}
        id={fieldId}
        name={input.name}
        value={input.value}
        disabled={input.disabled}
        placeholder={props.placeholder || ' '}
        aria-invalid={hasError.value ? true : undefined}
        aria-describedby={hasError.value ? errorId : undefined}
        onInput={handleInput}
        className={classx([
          TEXTAREA_CONFIGS.class,
          props.variant === 'filled' && TEXTAREA_CONFIGS.filledClass,
          TEXTAREA_CONFIGS.size[props.size!],
          hasError.value && TEXTAREA_CONFIGS.errorClass,
          props.className,
        ])}
      />
    ),
    'Textarea'
  );
}, 'Textarea');
