// ui/solid-form/src/inputs/DateTimePicker.tsx
import type { Bindable } from '@anchorlib/solid';
import type { JSX } from 'solid-js';
import { createInput } from './createInput.js';

export interface DateTimePickerProps extends Omit<JSX.InputHTMLAttributes<HTMLInputElement>, 'value'> {
  errorClass?: string;
  value?: Bindable<Date>;
}
export const DateTimePicker = createInput<DateTimePickerProps>('datetime-local');

// ui/react-form/src/inputs/DateTimePicker.tsx
import type { Bindable } from '@anchorlib/react';
import type { InputHTMLAttributes } from 'react';
import { createInput } from './createInput.js';

export interface DateTimePickerProps extends Omit<InputHTMLAttributes<HTMLInputElement>, 'value'> {
  value?: Bindable<Date>;
  errorClass?: string;
}
export const DateTimePicker = createInput<DateTimePickerProps>('datetime-local');
