// ui/solid-form/src/inputs/Slider.tsx
import type { Bindable } from '@anchorlib/solid';
import type { JSX } from 'solid-js';
import { createInput } from './createInput.js';

export interface SliderProps extends Omit<JSX.InputHTMLAttributes<HTMLInputElement>, 'value'> {
  errorClass?: string;
  value?: Bindable<number>;
}
export const Slider = createInput<SliderProps>('range');

// ui/react-form/src/inputs/Slider.tsx
import type { Bindable } from '@anchorlib/react';
import type { InputHTMLAttributes } from 'react';
import { createInput } from './createInput.js';

export interface SliderProps extends Omit<InputHTMLAttributes<HTMLInputElement>, 'value'> {
  errorClass?: string;
  value?: Bindable<number>;
}
export const Slider = createInput<SliderProps>('range');
