// ui/solid-form/src/inputs/TextInput.tsx
import type { Bindable } from '@anchorlib/solid';
import type { JSX } from 'solid-js';
import { createInput } from './createInput.js';

export interface TextInputProps extends Omit<JSX.InputHTMLAttributes<HTMLInputElement>, 'value'> {
  errorClass?: string;
  value?: Bindable<string>;
}
export const TextInput = createInput<TextInputProps>('text');

// ui/react-form/src/inputs/TextInput.tsx
import type { InputHTMLAttributes } from 'react';
import { createInput } from './createInput.js';
import type { Bindable } from '@anchorlib/react';

export interface TextInputProps extends Omit<InputHTMLAttributes<HTMLInputElement>, 'value'> {
  errorClass?: string;
  value?: Bindable<string>;
}
export const TextInput = createInput<TextInputProps>('text');
